image:
  file: .gitpod.Dockerfile

ports:
  # Grpc server
  - port: 9090
    onOpen: ignore
  # Metrics
  - port: 2112
    onOpen: open-preview

tasks:
 - init: >
#      composer install --no-interaction && ./vendor/bin/spiral get
   command: >
     ./spiral serve -v -d